version: '2.2'
  
services:
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    ports:
      - "3000:3000"
      - "5000:5000"
    privileged: true
    volumes:
       - jenkins-docker-certs:/certs/client
       - jenkins-data:/var/jenkins_home
       - $HOME:/home
    restart: always
    environment:
       DOCKER_TLS_CERTDIR: "/certs"
    networks:
       jenkins:
          aliases:
             - docker

  jenkins-blueocean:
    build:
      context: ./jenkins_build
    container_name: jenkins-blueocean
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
       - jenkins-docker-certs:/certs/client:ro
       - jenkins-data:/var/jenkins_home
       - $HOME:/home
    restart: always
    environment:
       DOCKER_HOST: tcp://docker:2376
       DOCKER_CERT_PATH: /certs/client
       DOCKER_TLS_VERIFY: 1
       JAVA_OPTS: "-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    networks:
       jenkins:

volumes:
  jenkins-docker-certs:
     name: jenkins-docker-certs
  jenkins-data:
     name: jenkins-data

networks:
  jenkins:
     name: jenkins
